### ISSUE TITLE
[Question] How to ignore first sync?

### ISSUE THREAD

**Issue by Friskygote** [tulir/mautrix-python#12]
Hello!
I've recently started using the mautrix framework and found it really useful for my goals, however one thing that I have hard time to grasp is how do I ignore the initial sync?    

[Here](https://github.com/tulir/mautrix-python/blob/master/mautrix/client/client.py#L262) the ignore_first_sync and ignore_initial_sync variables will cause the sync function to return effectively stopping the syncing in my experience, is this expected behavior? If yes, how to effectively ignore the initial sync without stopping the syncing? I'd expect the goal is to prevent handle_sync() from executing in this single sync run, which would mean using continue instead of return be the right thing to do (and moving self.is_first = False to the if statement just before continue). 

Thank you for creating the mautrix!

**Comment by tulir** [comment]
Huh... I wonder if this is what causes maubot to require restarting clients for them to work...

It's probably supposed to be a `continue`, will fix soon
