### ISSUE TITLE
make the base_url agnostic to trailing slashes

### ISSUE THREAD

**Issue by L0ric0** [tulir/mautrix-python#20]
at the moment if a `base_url` of the form `https://example.com/` is given to the Client api calls to `whoami` will fail. This is because the path that is build looks like this `https://example.com//_matrix/client/r0/account/whoami`.

**Comment by tulir** [comment]
Yeah, it should use yarl's `URL`. I didn't know about that when I made this, which is why it's currently just concatenating strings :D
